# Generated by Django 4.1.4 on 2023-01-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_advertisement_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='favorites',
        ),
    ]
