# Generated by Django 4.1.4 on 2023-01-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='creator',
            new_name='user_favorites',
        ),
    ]
