# Generated by Django 4.1.3 on 2022-12-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_scope_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='основной'),
            preserve_default=False,
        ),
    ]
