# Generated by Django 4.1.3 on 2022-11-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('image', models.ImageField(default='', upload_to='')),
                ('release_date', models.TextField()),
                ('lte_exists', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
